### ISSUE TITLE
Create parser

### ISSUE THREAD

**Issue by delvor** [MIT-Emerging-Talent/2024-group-02-cdsp#1]
- write parser
- clear data
- save to .csv file

**Comment by sapkotaatindra** [comment]
I see you have written parser, but just wondering how I could see the data.

**Comment by delvor** [comment]
It prints it out to the console, dict "table" .
Also needs to convert to csv and clear.

Did you run it? It works on your PC?

**Comment by sapkotaatindra** [comment]
yeh I ran it. I had to pip install selenium then it worked
