### ISSUE TITLE
Help: Need someone who will clean and combine gathered data

### ISSUE THREAD

**Issue by delvor** [MIT-Emerging-Talent/2024-group-02-cdsp#12]

**Comment by sapkotaatindra** [comment]
Hi Vlad, do you mean to combine two csv files that we have?

**Comment by delvor** [comment]
No. It will be about 130 different csv files after script. They all have
different columns and some of them not a csv data at all. We need to clean
them all and combine to a single file.

**Comment by mustafagunakan** [comment]
I cleaned the data and added it in the data-entry branch. Is ready to review.
