### ISSUE TITLE
Parcer.py issue

### ISSUE THREAD

**Issue by VolodymyrYakovenko** [MIT-Emerging-Talent/2024-group-02-cdsp#9]
@colevandersWands 

After inspecting parcer.py and trying to analyse **layoffs.fyi_20240206_043409.csv** some of problems were faced. 

Pandas couldn't correctly interpetate the code and faced a bunch of 'bad lines'. Hence, parcer partially works not as it should. 

![image](https://github.com/MIT-Emerging-Talent/2024-group-02-cdsp/assets/112565577/d7672c3b-b936-4315-af3b-2de8cf2b0013)

![image](https://github.com/MIT-Emerging-Talent/2024-group-02-cdsp/assets/112565577/edbc6190-235d-4499-b8b5-8e14915eee6a)

Is there any other way to make retrivieng data from "https://airtable.com/appzLUHyhTU5xpkdZ/shrclnXK0pfoGjtih/tblQ0U46nsYopm2CR" somehow easier(retrieving this data directly)? I tried to do that through Airtable API, but I couldn't because of lack of rights on this table. 
Sadly, we can't take .csv directly too.

**Comment by delvor** [comment]
Yes. I noticed it yesterday. Working on it. 

Some lines of data collects wrong. Some untyped symbols messed csv

**Comment by colevandersWands** [comment]
😬 I missed this in my notifications!  I noticed it now while reviewing your repo. 

My appologies.
